set define off;
set serveroutput on;
set feedback on;

prompt [DB INIT] start Oracle schema bootstrap

declare
  v_count number := 0;
begin
  select count(*) into v_count from user_tables where table_name = 'TB_ZONE0_EVENT_RAW';
  if v_count = 0 then
    execute immediate q'[
      create table TB_ZONE0_EVENT_RAW (
        event_ts        timestamp(6) not null,
        event_id        number generated by default on null as identity,
        zone_no         number(2) not null,
        symbol          varchar2(12),
        source          varchar2(40) not null,
        payload_json    clob not null,
        created_at      timestamp(6) default systimestamp not null,
        constraint CK_Z0_EVENT_ZONE check (zone_no between 0 and 9),
        constraint PK_TB_ZONE0_EVENT_RAW primary key (event_ts, event_id) using index local
      )
      partition by range (event_ts)
      interval (numtodsinterval(1, 'DAY'))
      (
        partition P_Z0_EVENT_BOOT values less than (timestamp '2026-01-01 00:00:00')
      )
    ]';
    dbms_output.put_line('created table TB_ZONE0_EVENT_RAW');
  else
    dbms_output.put_line('table TB_ZONE0_EVENT_RAW already exists');
  end if;
end;
/

declare
  v_count number := 0;
begin
  select count(*) into v_count from user_indexes where index_name = 'IX_Z0_EVENT_SYM_TS';
  if v_count = 0 then
    execute immediate 'create index IX_Z0_EVENT_SYM_TS on TB_ZONE0_EVENT_RAW(symbol, event_ts) local';
    dbms_output.put_line('created index IX_Z0_EVENT_SYM_TS');
  else
    dbms_output.put_line('index IX_Z0_EVENT_SYM_TS already exists');
  end if;
end;
/

declare
  v_count number := 0;
begin
  select count(*) into v_count from user_tables where table_name = 'TB_ZONE0_TG_CHANNELS';
  if v_count = 0 then
    execute immediate q'[
      create table TB_ZONE0_TG_CHANNELS (
        CHANNEL_ID         varchar2(64) not null,
        CHANNEL_USERNAME   varchar2(128) not null,
        CHANNEL_NAME       varchar2(256) not null,
        IS_ACTIVE          number(1) default 1 not null,
        CREATED_AT         timestamp(6) default systimestamp not null,
        UPDATED_AT         timestamp(6) default systimestamp not null,
        constraint PK_TB_ZONE0_TG_CHANNELS primary key (CHANNEL_ID),
        constraint CK_Z0_TG_ACTIVE check (IS_ACTIVE in (0, 1))
      )
    ]';
    dbms_output.put_line('created table TB_ZONE0_TG_CHANNELS');
  else
    dbms_output.put_line('table TB_ZONE0_TG_CHANNELS already exists');
  end if;
end;
/

declare
  v_count number := 0;
begin
  select count(*) into v_count from user_indexes where index_name = 'IX_Z0_TG_USERNAME';
  if v_count = 0 then
    execute immediate 'create unique index IX_Z0_TG_USERNAME on TB_ZONE0_TG_CHANNELS(CHANNEL_USERNAME)';
    dbms_output.put_line('created index IX_Z0_TG_USERNAME');
  else
    dbms_output.put_line('index IX_Z0_TG_USERNAME already exists');
  end if;
end;
/

declare
  v_count number := 0;
begin
  select count(*) into v_count from user_tables where table_name = 'TB_ZONE1_TECHNICAL_LOG';
  if v_count = 0 then
    execute immediate q'[
      create table TB_ZONE1_TECHNICAL_LOG (
        event_ts          timestamp(6) not null,
        log_id            number generated by default on null as identity,
        symbol            varchar2(12) not null,
        volume_power      number(9,2) not null,
        spike_ratio       number(9,2) not null,
        ma_divergence     number(9,4) not null,
        order_imbalance   number(9,4) not null,
        support_price     number(12,2) not null,
        resistance_price  number(12,2) not null,
        created_at        timestamp(6) default systimestamp not null,
        constraint PK_TB_ZONE1_TECH_LOG primary key (event_ts, log_id) using index local
      )
      partition by range (event_ts)
      interval (numtodsinterval(1, 'DAY'))
      (
        partition P_Z1_TECH_BOOT values less than (timestamp '2026-01-01 00:00:00')
      )
    ]';
    dbms_output.put_line('created table TB_ZONE1_TECHNICAL_LOG');
  else
    dbms_output.put_line('table TB_ZONE1_TECHNICAL_LOG already exists');
  end if;
end;
/

declare
  v_count number := 0;
begin
  select count(*) into v_count from user_indexes where index_name = 'IX_Z1_TECH_SYM_TS';
  if v_count = 0 then
    execute immediate 'create index IX_Z1_TECH_SYM_TS on TB_ZONE1_TECHNICAL_LOG(symbol, event_ts) local';
    dbms_output.put_line('created index IX_Z1_TECH_SYM_TS');
  else
    dbms_output.put_line('index IX_Z1_TECH_SYM_TS already exists');
  end if;
end;
/

declare
  v_count number := 0;
begin
  select count(*) into v_count from user_tables where table_name = 'TB_STOCK_FUNDAMENTAL';
  if v_count = 0 then
    execute immediate q'[
      create table TB_STOCK_FUNDAMENTAL (
        symbol                  varchar2(12) not null,
        risk_flag               varchar2(16) not null,
        issues_json             clob,
        has_cb_bw_issue         number(1) default 0 not null,
        has_krx_warning         number(1) default 0 not null,
        has_capital_impairment  number(1) default 0 not null,
        checked_at              timestamp(6) default systimestamp not null,
        source                  varchar2(20) default 'SYSTEM' not null,
        constraint PK_TB_STOCK_FUNDAMENTAL primary key (symbol),
        constraint CK_Z2_RISK_FLAG check (risk_flag in ('CLEAR', 'BLOCKED')),
        constraint CK_Z2_CB_BW check (has_cb_bw_issue in (0, 1)),
        constraint CK_Z2_KRX check (has_krx_warning in (0, 1)),
        constraint CK_Z2_CAPITAL check (has_capital_impairment in (0, 1))
      )
    ]';
    dbms_output.put_line('created table TB_STOCK_FUNDAMENTAL');
  else
    dbms_output.put_line('table TB_STOCK_FUNDAMENTAL already exists');
  end if;
end;
/

declare
  v_count number := 0;
begin
  select count(*) into v_count from user_indexes where index_name = 'IX_Z2_FUND_CHECKED_AT';
  if v_count = 0 then
    execute immediate 'create index IX_Z2_FUND_CHECKED_AT on TB_STOCK_FUNDAMENTAL(checked_at)';
    dbms_output.put_line('created index IX_Z2_FUND_CHECKED_AT');
  else
    dbms_output.put_line('index IX_Z2_FUND_CHECKED_AT already exists');
  end if;
end;
/

declare
  v_count number := 0;
begin
  select count(*) into v_count from user_tables where table_name = 'TB_ZONE3_PATTERN_LIBRARY';
  if v_count = 0 then
    execute immediate q'[
      create table TB_ZONE3_PATTERN_LIBRARY (
        pattern_id        varchar2(64) not null,
        klass             varchar2(16) not null,
        symbol            varchar2(12),
        pattern_vector    vector(1024, FLOAT32) not null,
        sample_ohlvc_json clob,
        created_at        timestamp(6) default systimestamp not null,
        updated_at        timestamp(6) default systimestamp not null,
        constraint PK_TB_ZONE3_PATTERN_LIB primary key (pattern_id),
        constraint CK_Z3_KLASS check (klass in ('CLASS_A', 'CLASS_B', 'CLASS_C'))
      )
    ]';
    dbms_output.put_line('created table TB_ZONE3_PATTERN_LIBRARY');
  else
    dbms_output.put_line('table TB_ZONE3_PATTERN_LIBRARY already exists');
  end if;
end;
/

declare
  v_count number := 0;
begin
  select count(*) into v_count from user_indexes where index_name = 'IX_Z3_CLASS_CREATED';
  if v_count = 0 then
    execute immediate 'create index IX_Z3_CLASS_CREATED on TB_ZONE3_PATTERN_LIBRARY(klass, created_at)';
    dbms_output.put_line('created index IX_Z3_CLASS_CREATED');
  else
    dbms_output.put_line('index IX_Z3_CLASS_CREATED already exists');
  end if;
end;
/

declare
  v_count number := 0;
begin
  select count(*) into v_count from user_indexes where index_name = 'IX_Z3_PATTERN_VEC';
  if v_count = 0 then
    begin
      execute immediate q'[
        create vector index IX_Z3_PATTERN_VEC
        on TB_ZONE3_PATTERN_LIBRARY(pattern_vector)
        organization inmemory neighbor graph
        distance cosine
      ]';
      dbms_output.put_line('created vector index IX_Z3_PATTERN_VEC');
    exception
      when others then
        dbms_output.put_line('skip IX_Z3_PATTERN_VEC: ' || sqlerrm);
    end;
  else
    dbms_output.put_line('index IX_Z3_PATTERN_VEC already exists');
  end if;
end;
/

declare
  v_count number := 0;
begin
  select count(*) into v_count from user_tables where table_name = 'TB_ZONE4_MADNESS_LOG';
  if v_count = 0 then
    execute immediate q'[
      create table TB_ZONE4_MADNESS_LOG (
        event_ts       timestamp(6) not null,
        log_id         number generated by default on null as identity,
        symbol         varchar2(12) not null,
        score          number(5,2) not null,
        stage          varchar2(16) not null,
        sentiment      number(5,2) not null,
        news_velocity  number(6,2) not null,
        source         varchar2(20) default 'LOCAL' not null,
        created_at     timestamp(6) default systimestamp not null,
        constraint PK_TB_ZONE4_MAD_LOG primary key (event_ts, log_id) using index local,
        constraint CK_Z4_STAGE check (stage in ('STAGE_1', 'STAGE_2', 'STAGE_3'))
      )
      partition by range (event_ts)
      interval (numtodsinterval(1, 'DAY'))
      (
        partition P_Z4_MAD_BOOT values less than (timestamp '2026-01-01 00:00:00')
      )
    ]';
    dbms_output.put_line('created table TB_ZONE4_MADNESS_LOG');
  else
    dbms_output.put_line('table TB_ZONE4_MADNESS_LOG already exists');
  end if;
end;
/

declare
  v_count number := 0;
begin
  select count(*) into v_count from user_indexes where index_name = 'IX_Z4_MAD_SYM_TS';
  if v_count = 0 then
    execute immediate 'create index IX_Z4_MAD_SYM_TS on TB_ZONE4_MADNESS_LOG(symbol, event_ts) local';
    dbms_output.put_line('created index IX_Z4_MAD_SYM_TS');
  else
    dbms_output.put_line('index IX_Z4_MAD_SYM_TS already exists');
  end if;
end;
/

declare
  v_count number := 0;
begin
  select count(*) into v_count from user_tables where table_name = 'TB_ZONE5_DECISION_LOG';
  if v_count = 0 then
    execute immediate q'[
      create table TB_ZONE5_DECISION_LOG (
        generated_at          timestamp(6) not null,
        decision_id           varchar2(64) not null,
        target_symbol         varchar2(12) not null,
        action                varchar2(8) not null,
        confidence_score      number(5,4) not null,
        reasoning             varchar2(1000) not null,
        suggested_weight_pct  number(5,2) not null,
        target_price          number(12,2),
        stop_price            number(12,2),
        source                varchar2(16) default 'RULE' not null,
        archive_json          clob,
        created_at            timestamp(6) default systimestamp not null,
        constraint PK_TB_ZONE5_DEC_LOG primary key (generated_at, decision_id) using index local,
        constraint CK_Z5_ACTION check (action in ('BUY', 'SELL', 'PASS'))
      )
      partition by range (generated_at)
      interval (numtodsinterval(1, 'DAY'))
      (
        partition P_Z5_DEC_BOOT values less than (timestamp '2026-01-01 00:00:00')
      )
    ]';
    dbms_output.put_line('created table TB_ZONE5_DECISION_LOG');
  else
    dbms_output.put_line('table TB_ZONE5_DECISION_LOG already exists');
  end if;
end;
/

declare
  v_count number := 0;
begin
  select count(*) into v_count from user_indexes where index_name = 'IX_Z5_DEC_SYM_TS';
  if v_count = 0 then
    execute immediate 'create index IX_Z5_DEC_SYM_TS on TB_ZONE5_DECISION_LOG(target_symbol, generated_at) local';
    dbms_output.put_line('created index IX_Z5_DEC_SYM_TS');
  else
    dbms_output.put_line('index IX_Z5_DEC_SYM_TS already exists');
  end if;
end;
/

declare
  v_count number := 0;
begin
  select count(*) into v_count from user_tables where table_name = 'TB_TRADE_HISTORY';
  if v_count = 0 then
    execute immediate q'[
      create table TB_TRADE_HISTORY (
        closed_at          timestamp(6) not null,
        trade_id           varchar2(64) not null,
        symbol             varchar2(12) not null,
        action             varchar2(8) not null,
        realized_pnl_pct   number(7,3) not null,
        win_flag           number(1) default 0 not null,
        zone5_archive_json clob not null,
        history_vector     vector(1024, FLOAT32),
        created_at         timestamp(6) default systimestamp not null,
        constraint PK_TB_TRADE_HISTORY primary key (closed_at, trade_id) using index local,
        constraint CK_Z6_ACTION check (action in ('BUY', 'SELL', 'PASS')),
        constraint CK_Z6_WIN_FLAG check (win_flag in (0, 1))
      )
      partition by range (closed_at)
      interval (numtoyminterval(1, 'MONTH'))
      (
        partition P_Z6_TRADE_BOOT values less than (timestamp '2026-01-01 00:00:00')
      )
    ]';
    dbms_output.put_line('created table TB_TRADE_HISTORY');
  else
    dbms_output.put_line('table TB_TRADE_HISTORY already exists');
  end if;
end;
/

declare
  v_count number := 0;
begin
  select count(*) into v_count from user_indexes where index_name = 'IX_Z6_TRADE_SYM_TS';
  if v_count = 0 then
    execute immediate 'create index IX_Z6_TRADE_SYM_TS on TB_TRADE_HISTORY(symbol, closed_at) local';
    dbms_output.put_line('created index IX_Z6_TRADE_SYM_TS');
  else
    dbms_output.put_line('index IX_Z6_TRADE_SYM_TS already exists');
  end if;
end;
/

declare
  v_count number := 0;
begin
  select count(*) into v_count from user_indexes where index_name = 'IX_Z6_TRADE_VEC';
  if v_count = 0 then
    begin
      execute immediate q'[
        create vector index IX_Z6_TRADE_VEC
        on TB_TRADE_HISTORY(history_vector)
        organization inmemory neighbor graph
        distance cosine
      ]';
      dbms_output.put_line('created vector index IX_Z6_TRADE_VEC');
    exception
      when others then
        dbms_output.put_line('skip IX_Z6_TRADE_VEC: ' || sqlerrm);
    end;
  else
    dbms_output.put_line('index IX_Z6_TRADE_VEC already exists');
  end if;
end;
/

prompt [DB INIT] schema bootstrap complete
